# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('make_wish', '0002_wish_granted_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
