# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_wish', '0004_wish_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liker', to='make_wish.User'),
        ),
    ]
