# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_wish', '0005_auto_20180924_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='likes',
            new_name='likes_sum',
        ),
        migrations.AlterField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='make_wish.User'),
        ),
    ]
